# Site settings
title: 金灵童子
email: wyforstudy@126.com
description: > # this means to ignore newlines until "baseurl:"
  talk is cheap, show me the code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wytrivail.github.io/" # the base hostname & protocol for your site
github_username:  wytrivail

# Build settings
markdown: kramdown
